# Generated by Django 4.1.7 on 2023-02-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_administrating', '0002_alter_chatuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_power', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_administrating.conversationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_administrating.chatuser')),
            ],
            options={
                'db_table': 'users2conversations',
            },
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='users',
            field=models.ManyToManyField(related_name='+', through='chat_administrating.ConversationThrough', to='auth_administrating.chatuser'),
        ),
    ]
