# Generated by Django 4.1.7 on 2023-02-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_administrating', '0002_alter_chatuser_id'),
        ('chat_administrating', '0002_alter_conversationthrough_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_administrating.chatuser'),
        ),
    ]
