# Generated by Django 4.1.7 on 2023-02-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_administrating', '0002_alter_chatuser_id'),
        ('chat_administrating', '0005_alter_conversationmodel_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmodel',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_administrating.chatuser'),
        ),
    ]
