# Generated by Django 4.1.7 on 2023-02-24 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_administrating', '0006_alter_conversationmodel_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
