# Generated by Django 4.1.7 on 2023-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_administrating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
